apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlas-volume
  labels:
    name: atlas-volume
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
  persistentVolumeReclaimPolicy: Retain
