apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doppler-volume-claim
  namespace: galaxy
  labels:
    name: doppler-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
