apiVersion: v1
kind: PersistentVolume
metadata:
  name: doppler-volume
  namespace: galaxy
  labels:
    name: doppler-volume
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/doppler/sqlite
