apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: atlas
  template:
    metadata:
      labels:
        name: atlas
    spec:
      containers:
      - name: atlas 
        image: edrodefeld/atlas
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: atlas-data
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: atlas-env-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: atlas-env-secrets
                key: POSTGRES_PASSWORD
      volumes:
        - name: atlas-data
          persistentVolumeClaim:
            claimName: atlas-volume-claim

