apiVersion: apps/v1
kind: Deployment
metadata:
  name: doppler
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: doppler
  template:
    metadata:
      labels:
        name: doppler
    spec:
      containers:
      - name: doppler
        image: edrodefeld/doppler
        imagePullPolicy: Always
        ports:
          - containerPort: 1323
        env:
          - name: S3_ENDPOINT
            value: "http://garage-s3.galaxy.svc.cluster.local:3900"
          - name: S3_REGION
            value: "garage"
          - name: S3_BUCKET
            value: "doppler-photos"
          - name: S3_USE_SSL
            value: "false"
          - name: DB_PATH
            value: "data/doppler.db"
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: doppler-s3-secrets
                key: S3_ACCESS_KEY_ID
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: doppler-s3-secrets
                key: S3_SECRET_ACCESS_KEY
        volumeMounts:
          - mountPath: /app/data
            name: doppler-data

      volumes:
        - name: doppler-data
          persistentVolumeClaim:
            claimName: doppler-volume-claim

