apiVersion: apps/v1
kind: Deployment
metadata:
  name: doppler
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: doppler
  template:
    metadata:
      labels:
        name: doppler
    spec:
      containers:
      - name: doppler
        image: edrodefeld/doppler
        imagePullPolicy: Always
        ports:
          - containerPort: 1323
        volumeMounts:
          - mountPath: /app/doppler.db
            name: doppler-data
            subPath: doppler.db

      volumes:
        - name: doppler-data
          persistentVolumeClaim:
            claimName: doppler-volume-claim

