apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreamflow-scheduler
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dreamflow-scheduler
  template:
    metadata:
      labels:
        name: dreamflow-scheduler
    spec:
      containers:
        - name: dreamflow-scheduler
          image: edrodefeld/dreamflow
          imagePullPolicy: IfNotPresent
          args: ["scheduler"]
          env:
            - name: AIRFLOW_PROJ_DIR
              valueFrom:
                secretKeyRef:
                  name: dreamflow-env-secrets
                  key: AIRFLOW_PROJ_DIR
            - name: AIRFLOW_HOME
              valueFrom:
                secretKeyRef:
                  name: dreamflow-env-secrets
                  key: AIRFLOW_HOME
            - name: AIRFLOW_CONN_POSTGRES_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: dreamflow-env-secrets
                  key: AIRFLOW_CONN_POSTGRES_DEFAULT
