apiVersion: apps/v1
kind: Deployment
metadata:
  name: enchiridion-redis
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: enchiridion-redis
  template:
    metadata:
      labels:
        name: enchiridion-redis
    spec:
      containers:
        - name: redis
          image: redis
          args: ["--requirepass", ""]
          ports:
            - containerPort: 6379
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: enchiridion-redis-pvc
