apiVersion: apps/v1
kind: Deployment
metadata:
  name: luna
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: luna
  template:
    metadata:
      labels:
        name: luna
    spec:
      containers:
        - name: luna
          image: edrodefeld/luna
          imagePullPolicy: Always 
          ports:
            - containerPort: 3000 
          envFrom:
            - configMapRef:
                name: luna-config
            - secretRef:
                name: luna-env-secrets

