apiVersion: apps/v1
kind: Deployment
metadata:
  name: ouroboros-server
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ouroboros-server
  template:
    metadata:
      labels:
        name: ouroboros-server
    spec:
      containers:
        - name: server
          image: woodpeckerci/woodpecker-server:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: ouroboros-env-secrets
          env:
            - name: WOODPECKER_OPEN
              value: "true"
            - name: WOODPECKER_ORGS
              value: "edrodefeld"
          volumeMounts:
            - name: server-data
              mountPath: /var/lib/woodpecker
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: server-data
          persistentVolumeClaim:
            claimName: ouroboros-server-pvc
