apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythology 
  namespace: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pythology
  template:
    metadata:
      labels:
        name: pythology
    spec:
      containers:
      - name: augur 
        image: edrodefeld/augur
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
          - protocol: TCP
        env:
          - name: AUGUR_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: augur-env-secrets
                key: AUGUR_SECRET_KEY
          - name: AUGUR_ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: augur-env-secrets
                key: AUGUR_ALLOWED_HOSTS
          - name: AUGUR_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: augur-env-secrets
                key: AUGUR_DB_PASSWORD
          - name: AUGUR_DB_USER
            valueFrom:
              secretKeyRef:
                name: augur-env-secrets
                key: AUGUR_DB_USER
          - name: AUGUR_DB_HOST
            valueFrom:
              secretKeyRef:
                name: augur-env-secrets
                key: AUGUR_DB_HOST
      - name: dreamflow
        image: edrodefeld/dreamflow
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
      - name: atlas 
        image: edrodefeld/atlas
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
          - protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: atlas-data
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: atlas-env-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: atlas-env-secrets
                key: POSTGRES_PASSWORD
      volumes:
        - name: atlas-data
          persistentVolumeClaim:
            claimName: atlas-volume-claim

