steps:
  apply-all:
    image: bitnami/kubectl
    commands:
      - echo "Applying all Kubernetes manifests..."
      # Apply ConfigMaps and Secrets first
      - kubectl apply -f configmaps/ -n galaxy || true
      - kubectl apply -f secrets/ -n galaxy || true
      # Apply RBAC
      - kubectl apply -f rbac/ || true
      # Apply Services
      - kubectl apply -f services/ -n galaxy || true
      # Apply Ingress
      - kubectl apply -f ingress.yml -n galaxy || true
      # Apply Deployments and StatefulSets
      - kubectl apply -f deployments/ -n galaxy || true
      # Apply Jobs
      - kubectl apply -f jobs/ -n galaxy || true
      - echo "All manifests applied!"
    when:
      - event: [push, manual]
        branch: main

  restart-deployments:
    image: bitnami/kubectl
    commands:
      - echo "Restarting all deployments in order..."
      # Core infrastructure first
      - kubectl rollout restart statefulset/garage -n galaxy || true
      - kubectl rollout restart deployment/atlas -n galaxy || true
      # Backend services
      - kubectl rollout restart deployment/augur -n galaxy || true
      # Frontend
      - kubectl rollout restart deployment/luna -n galaxy || true
      # Other services
      - kubectl rollout restart deployment/doppler -n galaxy || true
      - kubectl rollout restart deployment/kami -n galaxy || true
      - kubectl rollout restart deployment/enchiridion -n galaxy || true
      - kubectl rollout restart deployment/enchiridion-postgres -n galaxy || true
      - kubectl rollout restart deployment/enchiridion-redis -n galaxy || true
      # CI/CD infrastructure
      - kubectl rollout restart deployment/ouroboros-server -n galaxy || true
      - kubectl rollout restart deployment/ouroboros-agent -n galaxy || true
      # Dreamflow components
      - kubectl rollout restart deployment/dreamflow-webserver -n galaxy || true
      - kubectl rollout restart deployment/dreamflow-worker -n galaxy || true
      - kubectl rollout restart deployment/dreamflow-flower -n galaxy || true
      - kubectl rollout restart deployment/dreamflow-redis -n galaxy || true
      - echo "All deployments restarted!"
    when:
      - event: [push, manual]
        branch: main
        evaluate: 'CI_COMMIT_MESSAGE contains "[restart]" || CI_PIPELINE_EVENT == "manual"'
