steps:
  sync-secrets:
    image: bitnami/kubectl
    environment:
      BAO_ADDR: https://cuneiform.pinwheel.fan
      BAO_TOKEN:
        from_secret: cuneiform_token
    commands:
      - |
        # Install bao CLI
        cd /tmp
        curl -fsSL https://github.com/openbao/openbao/releases/download/v2.1.0/bao_2.1.0_Linux_x86_64.tar.gz | tar -xz
        chmod +x /tmp/bao
        
        echo "Syncing secrets from Cuneiform..."
        
        # Garage secrets
        /tmp/bao kv get -format=json galaxy-kv/prod/garage > /tmp/garage.json
        kubectl create secret generic garage-secrets \
          --from-literal=GARAGE_RPC_SECRET="$(cat /tmp/garage.json | jq -r '.data.data.rpc_secret')" \
          --from-literal=GARAGE_ADMIN_TOKEN="$(cat /tmp/garage.json | jq -r '.data.data.admin_token')" \
          -n galaxy --dry-run=client -o yaml | kubectl apply -f -
        
        # Ouroboros secrets
        /tmp/bao kv get -format=json galaxy-kv/prod/ouroboros > /tmp/ouroboros.json
        kubectl create secret generic ouroboros-env-secrets \
          --from-literal=WOODPECKER_HOST="https://ouroboros.pinwheel.fan" \
          --from-literal=WOODPECKER_AGENT_SECRET="$(cat /tmp/ouroboros.json | jq -r '.data.data.agent_secret')" \
          --from-literal=WOODPECKER_GITHUB_CLIENT="Ov23liIobhqrvlZAvDIM" \
          --from-literal=WOODPECKER_GITHUB_SECRET="$(cat /tmp/ouroboros.json | jq -r '.data.data.github_secret')" \
          --from-literal=WOODPECKER_DATABASE_DRIVER="sqlite3" \
          --from-literal=WOODPECKER_DATABASE_DATASOURCE="/var/lib/woodpecker/woodpecker.sqlite" \
          --from-literal=WOODPECKER_ADMIN="edrodefeld" \
          -n galaxy --dry-run=client -o yaml | kubectl apply -f -
        
        echo "✅ All secrets synced from Cuneiform"
    when:
      - event: [push, manual]
        branch: main

  apply-all:
    image: bitnami/kubectl
    commands:
      - echo "Applying app manifests (namespace-scoped only)..."
      # Apply only namespace-scoped resources that CI has permission for
      # Cluster-scoped resources (RBAC, PV, Ingress, ServiceAccounts) managed manually
      - |
        for file in apps/*/deployment.yml apps/*/service.yml apps/*/configmap.yml \
                    apps/*/statefulset.yml apps/*/*pvc.yml apps/*/job.yml; do
          [ -f "$file" ] && kubectl apply -f "$file" -n galaxy
        done
      - echo "App manifests applied :)"
    when:
      - event: [push, manual]
        branch: main

  restart-deployments:
    image: bitnami/kubectl
    commands:
      - echo "Restarting all resources..."
      - kubectl rollout restart statefulset -n galaxy
      - kubectl rollout restart deployment -n galaxy
      - echo "All resources restarted"
    when:
      - event: [push, manual]
        branch: main