apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-volume-claim
  namespace: galaxy
  labels:
    app: atlas
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
