apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlas-volume
  namespace: galaxy
  labels:
    type: local
    app: atlas
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
