apiVersion: batch/v1
kind: Job
metadata:
  name: dreamflow-db-init
  namespace: galaxy
spec:
  template:
    spec:
      serviceAccountName: dreamflow
      containers:
        - name: dreamflow-db-init
          image: edrodefeld/dreamflow
          command: ["airflow", "db", "init"]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: dreamflow-env-secrets
                  key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            - name: AIRFLOW_PROJ_DIR
              valueFrom:
                secretKeyRef:
                  name: dreamflow-env-secrets
                  key: AIRFLOW_PROJ_DIR
            - name: AIRFLOW_HOME
              valueFrom:
                secretKeyRef:
                  name: dreamflow-env-secrets
                  key: AIRFLOW_HOME
            - name: AIRFLOW__CELERY__BROKER_URL
              value: redis://dreamflow-redis-service.galaxy.svc.cluster.local
            - name: AIRFLOW_CONN_POSTGRES_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: dreamflow-env-secrets
                  key: AIRFLOW_CONN_POSTGRES_DEFAULT

      restartPolicy: OnFailure  # Retry if it fails
  backoffLimit: 3  # Optional: Number of retries before the job fails
