apiVersion: v1
kind: Service
metadata:
  name: dreamflow-webserver-service
  namespace: galaxy
spec:
  selector:
    name: dreamflow-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

