apiVersion: v1
kind: Service
metadata:
  name: dreamflow-worker-service
  namespace: galaxy
spec:
  selector:
    name: dreamflow-worker
  ports:
    - protocol: TCP
      port: 8793
      targetPort: 8793


