apiVersion: v1
kind: Service
metadata:
  name: ouroboros-service
  namespace: galaxy
spec:
  selector:
    name: ouroboros-server
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: grpc
      port: 9000
      targetPort: 9000

