apiVersion: v1
kind: Service
metadata:
  name: pythology-augur-service
  namespace: galaxy
spec:
  selector:
    name: pythology
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: pythology-dreamflow-service
  namespace: galaxy
spec:
  selector:
    name: pythology
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pythology-atlas-service
  namespace: galaxy
spec:
  selector:
    name: pythology
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
