apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: noctis-postgres
  namespace: galaxy
spec:
  serviceName: noctis-postgres-service
  replicas: 1
  selector:
    matchLabels:
      name: noctis-postgres
  template:
    metadata:
      labels:
        name: noctis-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: noctis-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: noctis-env-secrets
                  key: PREFECT_DB_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "prefect"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "prefect"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: noctis-postgres-pvc
