apiVersion: v1
kind: PersistentVolume
metadata:
  name: noctis-postgres-volume
  labels:
    name: noctis-postgres-volume
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/noctis/postgres
  persistentVolumeReclaimPolicy: Retain

