apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noctis-postgres-pvc
  namespace: galaxy
  labels:
    name: noctis-postgres-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
