apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-meta-pvc
  namespace: galaxy
  labels:
    app: garage
    volume: meta
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
