apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: galaxy
  labels:
    app: garage
spec:
  clusterIP: None
  selector:
    app: garage
  ports:
  - name: s3-api
    port: 3900
    targetPort: 3900
    protocol: TCP
  - name: rpc
    port: 3901
    targetPort: 3901
    protocol: TCP
  - name: web
    port: 3902
    targetPort: 3902
    protocol: TCP
  - name: admin
    port: 3903
    targetPort: 3903
    protocol: TCP
