apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-pvc
  namespace: galaxy
  labels:
    app: garage
    volume: data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
