apiVersion: v1
kind: Secret
metadata:
  name: augur-env-secrets
  namespace: galaxy
type: Opaque
stringData:
  # Django configuration
  AUGUR_SECRET_KEY: "CHANGE_ME"  # Generate with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
  AUGUR_DEBUG: "False"
  AUGUR_ALLOWED_HOSTS: "augur.pinwheel.fan,augur-service,augur-service.galaxy.svc.cluster.local"
  
  # CORS configuration
  AUGUR_CORS_ALLOWED_ORIGINS: "https://luna.pinwheel.fan"
  
  # Database credentials
  AUGUR_DB_HOST: "atlas-service.galaxy.svc.cluster.local"
  AUGUR_DB_USER: "CHANGE_ME"
  AUGUR_DB_PASSWORD: "CHANGE_ME"
  
  # Dreamflow/Airflow integration
  AUGUR_DREAMFLOW_HOST: "http://dreamflow-service.galaxy.svc.cluster.local:8080"
  AUGUR_DREAMFLOW_USER: "CHANGE_ME"
  AUGUR_DREAMFLOW_PASSWORD: "CHANGE_ME"


